package constant

const APPLICATION_NAME = "siakad"
const DB_DRIVER = "DB_DRIVER"
const DB_USERNAME = "DB_USERNAME"
const DB_PASSWORD = "DB_PASSWORD"
const DB_HOST = "DB_HOST"
const DB_NAME = "DB_NAME"
const CONTENT_TYPE = "Content-Type"
const APPLICATION_JSON = "application/json"
const PARAMETER_ID = "parameterId"
const PARAMETER_LIST_ID = "parameterListId"
const APP_HOST = "APP_HOST"
const APP_HOST_FULL = "APP_HOST_FULL"
const PREFIX_API = "/api"
const PAGE = "page"
const SIZE = "size"
const SEARCH = "search"
